[project]
name = 'BeeWelfare-and-Honey-Authenticity'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.apiary-certification-registry]
path = 'contracts/apiary-certification-registry.clar'
clarity_version = 3
epoch = '3.2'

[contracts.forage-and-exposure-reports]
path = 'contracts/forage-and-exposure-reports.clar'
clarity_version = 3
epoch = '3.2'

[contracts.hive-health-telemetry]
path = 'contracts/hive-health-telemetry.clar'
clarity_version = 3
epoch = '3.2'

[contracts.honey-origin-and-testing]
path = 'contracts/honey-origin-and-testing.clar'
clarity_version = 3
epoch = '3.2'

[contracts.label-verification]
path = 'contracts/label-verification.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
